### ISSUE TITLE
Adding a file reference or created/updated datetimes

### ISSUE THREAD

**Issue by markvaneijk** [spatie/sheets#20]
Awesome package! Great to have something flexible, which is totally Laravel style and works with Markdown and such.

I thought it would be a nice addition to have a some kind of reference to the original file and also to be able to retrieve an "created_at" and "updated_at" DateTime objects just like Eloquent has. But than based on the creation and updated time of the file itself.

**Comment by freekmurze** [comment]
Feel free to send a fully documented and tested PR.
