### ISSUE TITLE
FilesystemRepository does not behave like expected with SlugWithXyzParser

### ISSUE THREAD

**Issue by Gummibeer** [spatie/sheets#36]
My expectation by using `SlugWithOrderParser` or also `SlugWithDateParser` was that I still could do `Sheets::get('home')` and it will find `01.home.md`. But I have to call `Sheets::get('01.home')` to get the corresponding content. This means that I have to pass the order/date in the URL and if I change the order or date of a sheet I have to add redirects for to do not loose page rating and show the right content for posted links somewhere else.

To don't add a BC my idea would be to add a new method to the `FilesystemRepository` - for example `getBySlug()` which could the `Factory::$pathParser` property to create a regex and list all files via `files()` or `allFiles()`.

**Comment by Gummibeer** [comment]
I would like to reopen this issue because I still have this problem.

**Comment by sebastiandedeyne** [comment]
I'd be okay with making a breaking change here to use your suggested behaviour in v2.

**Comment by Gummibeer** [comment]
Do you want to work on it? Or should I provide a PR?

**Comment by sebastiandedeyne** [comment]
PR would be welcome, but I'll take care of it if you don't feel like it :)

**Comment by Gummibeer** [comment]
I will work on it tomorrow.
