### ISSUE TITLE
FilesystemRepository::all() return should have path as array key

### ISSUE THREAD

**Issue by Gummibeer** [spatie/sheets#37]
The `\Spatie\Sheets\Repositories\FilesystemRepository::all()` return should be keyed by the path. This is needed to render an index view which needs the path to link to the corresponding sheet.

**Comment by sebastiandedeyne** [comment]
Hmm I don't think I agree with this change. It's a collection of items, and I'd expect a numeric index for these.

A better solution would be to add the path to the `Sheet` object.
