### ISSUE TITLE
custom collection for sheets

### ISSUE THREAD

**Issue by Gummibeer** [spatie/sheets#56]
Hey,

like suggested in #52 I would like to add/use custom collection classes for the sheet collections which would allow to add a lot more granular/customized methods to find/filter sheets only limited by what collections can do and what the sheets provide.
Because sheets are now cached by default and provide also access to the path they were retrieved from this should be the better approach in my opinion because it doesn't limit the find logic to a single new method and what the package maintainer think will be a good way to find a sheet. Instead it allows the user to fully customize the logic.

I'm not sure but my super favorite would be the possibility to bind a collection by sheet collection.
So I think that we would need a new config key, by default a new `SheetCollection` should be used/added which allows to add macros or rebind it to add sheet collection logic to all sheets collections.
If more granular logic is needed the user is free to set the new config value to his `PostSheetCollection` for example.

**RFC**:
* add a new optional config key to the sheet collection array `collection_class`
* add a `SheetCollection` which is used by default and bound to the container
* use the default sheet collection from container or the configured one in `FilesystemRepository`

**Comment by sebastiandedeyne** [comment]
Do you have a few code examples of features you'd add to a custom collection class as a package user? What are you missing from current collectins?

**Comment by Gummibeer** [comment]
Something like model scopes.
Let's assume the most common(?) scenario - a collection of recipes, blog articles or similar.

Now I have common filters like `$posts->filter(fn(Post $post): bool => in_array($this->slug, $post->categories))` - which would be easier if I could add a `byCategory(string $category)` method to the collection and call it `$posts->byCategory($category)`.
Or I want to add a `paginate()` method like on the eloquent query builder (possibly a laravel core topic).

The "problem" is that eloquent allows to define these methods on the model class and pipe/call them from the query builder.
I wouldn't want to add functionality like this because it adds a massive level of complexity and still limits the user to the cases we added. So let's say we add something like `scopes` but the user also wants a `categories()` method on the post collection that runs:
```php
$posts
    ->map(fn(Post $post): Collection => $post->categories())
    ->collapse()
    ->unique('slug');
```
So custom collections will be the last part in this package to allow full flexibility.
Sure I could also override the repository right now, but this would limit me to the first level, so I can't do `$posts->byAuthor('Gummibeer')->byDate(now())->byCategory('laravel')`.

For me the collections are the query builder for sheets - with LazyCollections even more - but also the current one because of the cached sheet instances which makes lazy collections somehow useless. 🤔
