### ISSUE TITLE
Release 1.7.3 has the wrong title

### ISSUE THREAD

**Issue by olssonm** [spatie/sheets#67]
Just encountered an issue when trying to update an old project; saw in the releases-section that [1.8.0 was out](https://github.com/spatie/sheets/releases/tag/1.7.3) and tried to install it.

But kept getting:

```
 [InvalidArgumentException]
Could not find package spatie/sheets in a version matching "^1.8.0" and a stability matching "dev".
```

Seems that the release is actually tagged with 1.7.3? I should have checked more thoroughly but I was very confused for a while 😀

**Comment by freekmurze** [comment]
Let me tag an 1.8.0
