### ISSUE TITLE
Property type not supported in Livewire

### ISSUE THREAD

**Issue by mr-technik** [spatie/sheets#75]
I am building a Livewire application, and I really want to use Sheets for my blog posts. I am storing them as MD files and then using Sheets to display them.

However, when I try to get the posts, I get the below error:

```
Property type not supported in Livewire for property...
```

Any idea how to fix this or get around this.

**Comment by sebastiandedeyne** [comment]
Could you share a repository with the issue, or a more complete code example to reproduce?

**Comment by mr-technik** [comment]
I am trying to retrieve a collection. It works in a regular Controller and a View but when I put it in to a LiveWire Component I get the error.

```
class Articles extends Component
{
    public $articles;

    public function render()
    {
        $this->articles = Sheets::collection('article')->all();

        return view('livewire.article.index');
    }
}
```

```
Property type not supported in Livewire for property: [{"date":"2023-12-27T00:00:00.000000Z","slug":"amateur-dramatics-history","title":"The History of Amateur Dramatics","meta_description":"Amateur dramatics, often called community or amateur theatre, has a rich and vibrant history spanning centuries. The roots of amateur dramatics can be traced back to ancient civilisations.","author":"Tom","featured_image":"blog\/featured\/sutton-amdram-1902.jpg","featured_image_caption":"<a href=\"https:\/\/sadc.co.uk\/history\/\">Sutton Amateur Dramatic Club<\/a>, a comedy called \"School\" by T W Robertson, 1902.","contents":{}}]
```

**Comment by sebastiandedeyne** [comment]
Livewire does [not support all objects as properties](https://livewire.laravel.com/docs/properties#supported-property-types).

You can write a [custom synthesizer](https://livewire.laravel.com/docs/synthesizers#registering-a-custom-synthesizer) to serialize & deserialize the sheet to use it with Livewire. If additional methods in this package would make that easier, we can add them.

**Comment by mr-technik** [comment]
It would make it easier but I think I shall just rewrite my entire app without Livewire.
