### ISSUE TITLE
convertToHtml deprecated

### ISSUE THREAD

**Issue by emergencyreports** [spatie/sheets#76]
`LOG.warning: Since league/commonmark 2.2.0: Calling "convertToHtml()" on a League\CommonMark\MarkdownConverter class is deprecated, use "convert()" instead. in /path/to/app/vendor/symfony/deprecation-contracts/function.php on line 25`

**Comment by freekmurze** [comment]
Feel free to send a PR to fix this!

**Comment by freekmurze** [comment]
Fixed in the latest version thanks to your PR 👍
